### ISSUE TITLE
Missing imports in HomeController.java

### ISSUE THREAD

**Issue by krinkere** [uaihebert/uaicontacts#1]
When I tried to build it, it failed since imports for ResponseEntity was missing in HomeController.java. 

package uaiContacts.controller;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Controller
@RequestMapping(value = "/")
public class HomeController {

```
@RequestMapping(method = {RequestMethod.GET, RequestMethod.POST, RequestMethod.DELETE, RequestMethod.PUT})
public String redirect(){
    return "redirect:/protected/home";
}

@RequestMapping(method = {RequestMethod.GET, RequestMethod.POST, RequestMethod.DELETE, RequestMethod.PUT}, produces = "application/json")
public ResponseEntity<?> doGetAjax() {
    return new ResponseEntity<Object>(HttpStatus.FORBIDDEN);
}    
```

}

**Comment by uaihebert** [comment]
Hello Thanks for the tip, I just pushed the correction.

[=

**Comment by krinkere** [comment]
Thank you! :+1:
